```{r}
#import data and detection limts from csv's

data1 <- read.csv("MarijnData.csv", sep =";")

dl <- read.csv("MarijnDetLim.csv", sep =";")

```

```{r}
#make all values numeric

data1[] <- lapply(data1, function(col) {sapply(col, function(x) {if (grepl("[a-zA-Z]", x)) {
  x} else {as.numeric(gsub(",", ".", x))}})})

dl[] <- lapply(dl, function(col) {sapply(col, function(x) {if (grepl("[a-zA-Z]", x)) {
  x} else {as.numeric(gsub(",", ".", x))}})})

```

```{r}
#check if measurements are >= detection limits

data_checked <- data1

data_checked[] <- Map(function(meas, dl) {
  ifelse(is.na(meas) | is.na(dl), NA,           
         ifelse(meas < dl, NA_real_, meas))   
}, data1, dl)

```

```{r}
no_std <- data_checked %>% select(-matches("^(N612|N610)\\.")) 
rownames(no_std) <- no_std[,1]
no_std <- no_std[,-1]
#png("heatmap.png", units="cm", width=25, height=15, res=300)
heatmap(as.matrix(no_std), Rowv = NA, Colv = NA, margins = c(10,2), cexCol = 0.33)
```

```{r}
library(dplyr)

data_cleaned <- data_checked %>%
  select(-Element, -starts_with("N6")) %>%
  slice(c(1, 2, 8, 9, 11, 12))
  
```

```{r}
data_summed <- data_cleaned %>%
  slice(1:6) %>%
  mutate(group = rep(1:3, each = 2)) %>%
  group_by(group) %>%
  summarise(across(everything(), ~ sum(.x, na.rm = TRUE))) %>%
  select(-group)

data_summed <- t(data_summed)
data_summed <- as.data.frame(data_summed)
colnames(data_summed) <- c("Ca", "Sr", "Ba")
```

```{r}
data_summed$Genus <- ifelse(grepl("noth", rownames(data_summed), ignore.case = TRUE), "Nothosaurus",
                     ifelse(grepl("acr", rownames(data_summed), ignore.case = TRUE), "Acrodus",
                       ifelse(grepl("colo", rownames(data_summed), ignore.case = TRUE), "Colobodus",
                         ifelse(grepl("gyro", rownames(data_summed), ignore.case = TRUE), "Gyrolepis",
                           ifelse(grepl("saur", rownames(data_summed), ignore.case = TRUE), "Saurichthys",
                             NA)))))
data_summed$Genus <- as.factor(data_summed$Genus)
```

```{r}
resultsBa <- aov(Ba/Ca~Genus, data_summed)
TukeyHSD(resultsBa)

resultsSr <- aov(Sr/Ca~Genus, data_summed)
TukeyHSD(resultsSr)
```

```{r}
library(ggplot2)
library(tibble)
library(ggforce)
data_summed$Specimen <- gsub("\\.\\d+$", "", rownames(data_summed))

#plot ratios

png("totalspread.png", units="cm", width=25, height=15, res=300)
ggplot(data_summed, aes(x = Sr/Ca*1000, y = Ba/Ca*1000, color = Specimen, shape = Specimen)) +
  geom_mark_ellipse(aes(group = Specimen), expand = unit(1.5, "mm"), alpha = 1
  ) +
  geom_point(size = 2.5, alpha = 1) +
  labs(
    x = "Sr/Ca Ratio × 1000",
    y = "Ba/Ca Ratio × 1000",
    color = "Specimen",
    shape = "Specimen"
  ) +
  theme_bw(base_size = 13) +
  scale_shape_manual(values = c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10))
```

```{r}
#plot ratios without outliers

png("totalspreadzoomed.png", units="cm", width=25, height=15, res=300)
ggplot(data_summed[-c(28, 29, 30, 57),], aes(x = Sr/Ca*1000, y = Ba/Ca*1000, color = Specimen, shape = Specimen)) +
  geom_mark_ellipse(aes(group = Specimen), expand = unit(1.5, "mm"), alpha = 1
  ) +
  geom_point(size = 2.5, alpha = 1) +
  labs(
    x = "Sr/Ca Ratio × 1000",
    y = "Ba/Ca Ratio × 1000",
    color = "Specimen",
    shape = "Specimen"
  ) +
  theme_bw(base_size = 13) +
  scale_shape_manual(values = c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10))
```
